//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Codigo { get; set; }
        public string Contrasena { get; set; }
        public string Numero_de_Identidad { get; set; }
        public string Nombre_Completo { get; set; }
        public string Genero { get; set; }
        public string Corre_Electronico { get; set; }
        public string Telefono { get; set; }
        public string Rol { get; set; }
    }
}
